[package]
name = "ecdh-edwards-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
curve25519-dalek = { version = "4.1.1" }
